name: food_recipe_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  cached_network_image: null
  carousel_slider: ^4.2.1
  chewie: ^1.5.0
  cloud_firestore: ^3.1.11
  cupertino_icons: ^1.0.2
  firebase_storage: null
  flashy_tab_bar2: ^0.0.6
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^1.8.1
  flutter_iconly: ^1.0.2
  flutter_screenutil: null
  firebase_core_platform_interface: 4.5.1
  get: null
  get_storage: ^2.1.1
  http: null
  image_picker: ^0.8.9
  lottie: ^2.3.2
  paginate_firestore: ^1.0.3+1
  path_provider: ^2.0.15
  pull_to_refresh: ^2.0.0
  share_plus: null
  url_launcher: ^6.1.11
  video_player: ^2.6.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/category/
    - assets/animation/

  fonts:
    - family: gilroy-bold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
    - family: GilroyMedium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
